server:
  port: 8801
spring:
  application:
    name: config-server
  cloud:
    config:
      server:
        git:
          uri: git@github.com:songshuiyang/spring-cloud-parent.git
          searchPaths: /**/gitconfig
eureka:
  instance:
    hostname: localhost
  client:
    service-url:
      defaultZone: http://localhost:9010/eureka/